################################################################################
# Victoria Logs Single configuration
################################################################################

# Uncomment if not using otel collector for logs
# vector:
#   enabled: true
