apiVersion: v1
kind: Service
metadata:
  name: service-core-sv
  namespace: default
spec:
  selector:
    app: service-core
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: grpc
      protocol: TCP
      port: 8443
      targetPort: grpc
