apiVersion: v1
kind: Service
metadata:
  name: service-client-sv
  namespace: default
spec:
  selector:
    app: service-client
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
