apiVersion: v1
kind: Service
metadata:
  name: service-admin-sv
  namespace: default
spec:
  selector:
    app: service-admin
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: sse
      protocol: TCP
      port: 8443
      targetPort: sse
