name: Build and Deploy

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      IMAGE_R:
        required: true
        type: string
      IMAGE_RC:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
      DIRECTORY:
        required: true
        type: string
      CONTEXT:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.release.prerelease == true && 'release-candidate' || 'release' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create private key file
        run: echo "${{ secrets.PRIVATE_KEY_PEM }}" > ${{ inputs.DIRECTORY }}/private.pem
      - name: Create public key file
        run: echo "${{ secrets.PUBLIC_KEY_PEM }}" > ${{ inputs.DIRECTORY }}/public.pem

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DIRECTORY }}/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ inputs.REGISTRY }}/${{ github.repository }}/${{ github.event.release.prerelease == true && inputs.IMAGE_RC || inputs.IMAGE_R }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Clean up PEM files
        if: always()
        run: |
          rm -f ${{ inputs.DIRECTORY }}/private.pem
          rm -f ${{ inputs.DIRECTORY }}/public.pem

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.release.prerelease == true && 'release-candidate' || 'release' }}
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Redeploy
        run : |
          echo "Redeploying..."
          kubectl rollout restart deployment ${{ inputs.SERVICE }}
          kubectl rollout status deployment ${{ inputs.SERVICE }}
